neptune:
    api_token: ''
options:
    dataset:
        train: 'trainvalset'
        val: 'testset'
        test: 'testset'
        train_val_ratio: 0.9
    num_classes: 10
    resnet:
        depth: 40
        widen: 2
    num_workers: 4
    device: 'cuda'
    max_epochs: 100
    use_tqdm: False
configs:
    dropout_rate: 'tune.quniform(0.0, 0.5, 0.1)'
    weight_decay: 'tune.qloguniform(1e-4, 1e-2, 5e-5)'
    batch_size: 'tune.choice([32, 64, 128, 256, 512, 1024])'
    lr_init: 'tune.qloguniform(1e-3, 5e-1, 5e-4)'
    lr_gamma: 'tune.quniform(0.1, 1.0, 0.1)'
    lr_stepsize: 'tune.qrandint(10, 100, 5)'
